# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180512_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='serialNumberVideo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
