# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post_serialnumbervideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publishPost',
            field=models.BooleanField(default=True),
        ),
    ]
