# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20180513_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nameLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
